# Generated by Django 4.0.6 on 2022-08-18 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_code', models.CharField(max_length=20, verbose_name='Артикул')),
                ('name', models.CharField(max_length=20, verbose_name='Наименование')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('comment', models.TextField(verbose_name='Комментарий')),
            ],
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Марка автозапчасти')),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=50, verbose_name='Производитель')),
            ],
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('мodel', models.CharField(max_length=50, verbose_name='Модель марки')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20, verbose_name='Роль')),
            ],
        ),
        migrations.CreateModel(
            name='Streets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50, verbose_name='Улица')),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Наименование организации')),
                ('INN', models.IntegerField(verbose_name='ИНН')),
                ('CIO', models.IntegerField(verbose_name='КПП')),
                ('FullNameManager', models.CharField(max_length=150, verbose_name='ФИО руководителя')),
                ('telephone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.CharField(max_length=30, verbose_name='Эл почта')),
            ],
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('id_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autodocapp.roles', verbose_name='Роль')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoreDepartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.CharField(max_length=10, verbose_name='Дом')),
                ('telephone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('id_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autodocapp.cities', verbose_name='Город')),
                ('id_street', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autodocapp.streets', verbose_name='Улица')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('DateOfSale', models.DateField(verbose_name='Дата продажи')),
                ('id_autoParts', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autodocapp.autoparts', verbose_name='Автозапчасть')),
                ('id_suppliers', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autodocapp.storedepartments', verbose_name='Отдел магазина')),
            ],
        ),
        migrations.CreateModel(
            name='BrandsAndModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autodocapp.brands', verbose_name='Марка автомобиля')),
                ('id_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autodocapp.models', verbose_name='Модель')),
            ],
        ),
        migrations.CreateModel(
            name='AutoPartsInStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Наименование')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('id_StoreDepartment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autodocapp.autoparts', verbose_name='Автозапчасть')),
                ('id_brand_and_models', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autodocapp.brandsandmodels', verbose_name='Автомобиль')),
                ('id_manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autodocapp.manufacturers', verbose_name='Производитель')),
            ],
        ),
        migrations.AddField(
            model_name='autoparts',
            name='id_brand_and_models',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autodocapp.brandsandmodels', verbose_name='Автомобиль'),
        ),
        migrations.AddField(
            model_name='autoparts',
            name='id_manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autodocapp.manufacturers', verbose_name='Производитель'),
        ),
    ]
